s = input('Type anything: ')
print(f'Type: {type(s)}')
print(f'Has spaces? {s.isspace()}')
print(f'Is number? {s.isnumeric()}')
print(f'Is aplhabetic? {s.isalpha()}')
print(f'Is aplhanumeric? {s.isalnum()}')
print(f'Is in uppercase? {s.isupper()}')
print(f'Is in lowercase? {s.islower()}')
print(f'Is capitalized? {s.istitle()}')
